signaling:
  name: "signaling"
  host: "0.0.0.0"
  rep_port: 5555
  pub_port: 5556
  zmq:
    protocol: "tcp"
    bind_address: "*"
    heartbeat_interval: 30

message_storage:
  db_type: "postgresql"
  db_host: "localhost"
  db_port: 5432
  db_user: "postgres"
  db_password: "postgres"
  dbname: "lunaricorn"
  subscriber_timeout: 300
  max_events: 1000
