signaling:
  name: "signaling"
  host: "0.0.0.0"
  port: 5555
  zmq:
    protocol: "tcp"
    bind_address: "*"
    max_connections: 100
    heartbeat_interval: 30
    timeout: 60

message_storage:
  db_type: "postgresql"
  db_host: "localhost"
  db_port: 5432
  db_user: "postgres"
  db_password: "postgres"
  dbname: "lunaricorn"
