# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import datastorage_pb2 as datastorage__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in datastorage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushData = channel.unary_unary(
                '/datastorage.DataStorageService/PushData',
                request_serializer=datastorage__pb2.PushDataRequest.SerializeToString,
                response_deserializer=datastorage__pb2.PushDataResponse.FromString,
                _registered_method=True)
        self.PushMeta = channel.unary_unary(
                '/datastorage.DataStorageService/PushMeta',
                request_serializer=datastorage__pb2.PushMetaRequest.SerializeToString,
                response_deserializer=datastorage__pb2.PushMetaResponse.FromString,
                _registered_method=True)
        self.FetchMeta = channel.unary_unary(
                '/datastorage.DataStorageService/FetchMeta',
                request_serializer=datastorage__pb2.FetchMetaRequest.SerializeToString,
                response_deserializer=datastorage__pb2.FetchMetaResponse.FromString,
                _registered_method=True)
        self.FetchData = channel.unary_unary(
                '/datastorage.DataStorageService/FetchData',
                request_serializer=datastorage__pb2.FetchDataRequest.SerializeToString,
                response_deserializer=datastorage__pb2.FetchDataResponse.FromString,
                _registered_method=True)


class DataStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushData': grpc.unary_unary_rpc_method_handler(
                    servicer.PushData,
                    request_deserializer=datastorage__pb2.PushDataRequest.FromString,
                    response_serializer=datastorage__pb2.PushDataResponse.SerializeToString,
            ),
            'PushMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMeta,
                    request_deserializer=datastorage__pb2.PushMetaRequest.FromString,
                    response_serializer=datastorage__pb2.PushMetaResponse.SerializeToString,
            ),
            'FetchMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchMeta,
                    request_deserializer=datastorage__pb2.FetchMetaRequest.FromString,
                    response_serializer=datastorage__pb2.FetchMetaResponse.SerializeToString,
            ),
            'FetchData': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchData,
                    request_deserializer=datastorage__pb2.FetchDataRequest.FromString,
                    response_serializer=datastorage__pb2.FetchDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datastorage.DataStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datastorage.DataStorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datastorage.DataStorageService/PushData',
            datastorage__pb2.PushDataRequest.SerializeToString,
            datastorage__pb2.PushDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datastorage.DataStorageService/PushMeta',
            datastorage__pb2.PushMetaRequest.SerializeToString,
            datastorage__pb2.PushMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datastorage.DataStorageService/FetchMeta',
            datastorage__pb2.FetchMetaRequest.SerializeToString,
            datastorage__pb2.FetchMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datastorage.DataStorageService/FetchData',
            datastorage__pb2.FetchDataRequest.SerializeToString,
            datastorage__pb2.FetchDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
