# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datastorage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'datastorage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61tastorage.proto\x12\x0b\x64\x61tastorage\",\n\x0fPushDataRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"#\n\x10PushDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x0fPushMetaRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04meta\x18\x02 \x01(\x0c\"#\n\x10PushMetaResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x10\x46\x65tchMetaRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x11\x46\x65tchMetaResponse\x12\x0c\n\x04meta\x18\x01 \x01(\x0c\"\x1f\n\x10\x46\x65tchDataRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x11\x46\x65tchDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xbe\x02\n\x12\x44\x61taStorageService\x12G\n\x08PushData\x12\x1c.datastorage.PushDataRequest\x1a\x1d.datastorage.PushDataResponse\x12G\n\x08PushMeta\x12\x1c.datastorage.PushMetaRequest\x1a\x1d.datastorage.PushMetaResponse\x12J\n\tFetchMeta\x12\x1d.datastorage.FetchMetaRequest\x1a\x1e.datastorage.FetchMetaResponse\x12J\n\tFetchData\x12\x1d.datastorage.FetchDataRequest\x1a\x1e.datastorage.FetchDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datastorage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHDATAREQUEST']._serialized_start=34
  _globals['_PUSHDATAREQUEST']._serialized_end=78
  _globals['_PUSHDATARESPONSE']._serialized_start=80
  _globals['_PUSHDATARESPONSE']._serialized_end=115
  _globals['_PUSHMETAREQUEST']._serialized_start=117
  _globals['_PUSHMETAREQUEST']._serialized_end=161
  _globals['_PUSHMETARESPONSE']._serialized_start=163
  _globals['_PUSHMETARESPONSE']._serialized_end=198
  _globals['_FETCHMETAREQUEST']._serialized_start=200
  _globals['_FETCHMETAREQUEST']._serialized_end=231
  _globals['_FETCHMETARESPONSE']._serialized_start=233
  _globals['_FETCHMETARESPONSE']._serialized_end=266
  _globals['_FETCHDATAREQUEST']._serialized_start=268
  _globals['_FETCHDATAREQUEST']._serialized_end=299
  _globals['_FETCHDATARESPONSE']._serialized_start=301
  _globals['_FETCHDATARESPONSE']._serialized_end=334
  _globals['_DATASTORAGESERVICE']._serialized_start=337
  _globals['_DATASTORAGESERVICE']._serialized_end=655
# @@protoc_insertion_point(module_scope)
