
@apiUrl = http://{{lunaricordUrl}}:5557

# @name health
GET http://{{lunaricordUrl}}:5557/health

###

# @name index
GET {{apiUrl}}


###

# @name browse - full req
POST http://{{lunaricordUrl}}:5557/v1/browse HTTP/1.1
Content-Type: application/json
Accept-Encoding: br, gzip, deflate

{
    "timestamp":0,
    "event_types": ["a", "b"],
    "sources": ["c", "d"],
    "affected": ["e", "f"],
    "tags": ["g", "h"],
    "limit" : 1000
}


###

# @name browse - ctime only
POST http://{{lunaricordUrl}}:5557/v1/browse HTTP/1.1
Content-Type: application/json
Accept-Encoding: br, gzip, deflate

{
    "timestamp":0
}