@apiUrl = http://{{lunaricordUrl}}:5557

# @name health
GET http://{{lunaricordUrl}}:5557/health

###

# @name index
GET http://{{lunaricordUrl}}:5557/

###

# @name clients
GET http://{{lunaricordUrl}}:5557/v1/stat/clients

