# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import datastorage_pb2 as datastorage__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in datastorage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrbDataServiceStub(object):
    """Обновленный протокол с поддержкой Orb объектов
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushData = channel.unary_unary(
                '/lunaricorn.orb.OrbDataService/PushData',
                request_serializer=datastorage__pb2.PushDataRequest.SerializeToString,
                response_deserializer=datastorage__pb2.PushResponse.FromString,
                _registered_method=True)
        self.PushMeta = channel.unary_unary(
                '/lunaricorn.orb.OrbDataService/PushMeta',
                request_serializer=datastorage__pb2.PushMetaRequest.SerializeToString,
                response_deserializer=datastorage__pb2.PushResponse.FromString,
                _registered_method=True)
        self.FetchData = channel.unary_unary(
                '/lunaricorn.orb.OrbDataService/FetchData',
                request_serializer=datastorage__pb2.FetchRequest.SerializeToString,
                response_deserializer=datastorage__pb2.FetchDataResponse.FromString,
                _registered_method=True)
        self.FetchMeta = channel.unary_unary(
                '/lunaricorn.orb.OrbDataService/FetchMeta',
                request_serializer=datastorage__pb2.FetchRequest.SerializeToString,
                response_deserializer=datastorage__pb2.FetchMetaResponse.FromString,
                _registered_method=True)
        self.PushOrbData = channel.unary_unary(
                '/lunaricorn.orb.OrbDataService/PushOrbData',
                request_serializer=datastorage__pb2.OrbDataRequest.SerializeToString,
                response_deserializer=datastorage__pb2.OrbResponse.FromString,
                _registered_method=True)
        self.PushOrbMeta = channel.unary_unary(
                '/lunaricorn.orb.OrbDataService/PushOrbMeta',
                request_serializer=datastorage__pb2.OrbMetaRequest.SerializeToString,
                response_deserializer=datastorage__pb2.OrbResponse.FromString,
                _registered_method=True)
        self.FetchOrbData = channel.unary_unary(
                '/lunaricorn.orb.OrbDataService/FetchOrbData',
                request_serializer=datastorage__pb2.FetchOrbRequest.SerializeToString,
                response_deserializer=datastorage__pb2.OrbDataResponse.FromString,
                _registered_method=True)
        self.FetchOrbMeta = channel.unary_unary(
                '/lunaricorn.orb.OrbDataService/FetchOrbMeta',
                request_serializer=datastorage__pb2.FetchOrbRequest.SerializeToString,
                response_deserializer=datastorage__pb2.OrbMetaResponse.FromString,
                _registered_method=True)


class OrbDataServiceServicer(object):
    """Обновленный протокол с поддержкой Orb объектов
    """

    def PushData(self, request, context):
        """Существующие методы для совместимости
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushOrbData(self, request, context):
        """Новые методы для работы с Orb объектами
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushOrbMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchOrbData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchOrbMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrbDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushData': grpc.unary_unary_rpc_method_handler(
                    servicer.PushData,
                    request_deserializer=datastorage__pb2.PushDataRequest.FromString,
                    response_serializer=datastorage__pb2.PushResponse.SerializeToString,
            ),
            'PushMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMeta,
                    request_deserializer=datastorage__pb2.PushMetaRequest.FromString,
                    response_serializer=datastorage__pb2.PushResponse.SerializeToString,
            ),
            'FetchData': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchData,
                    request_deserializer=datastorage__pb2.FetchRequest.FromString,
                    response_serializer=datastorage__pb2.FetchDataResponse.SerializeToString,
            ),
            'FetchMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchMeta,
                    request_deserializer=datastorage__pb2.FetchRequest.FromString,
                    response_serializer=datastorage__pb2.FetchMetaResponse.SerializeToString,
            ),
            'PushOrbData': grpc.unary_unary_rpc_method_handler(
                    servicer.PushOrbData,
                    request_deserializer=datastorage__pb2.OrbDataRequest.FromString,
                    response_serializer=datastorage__pb2.OrbResponse.SerializeToString,
            ),
            'PushOrbMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.PushOrbMeta,
                    request_deserializer=datastorage__pb2.OrbMetaRequest.FromString,
                    response_serializer=datastorage__pb2.OrbResponse.SerializeToString,
            ),
            'FetchOrbData': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchOrbData,
                    request_deserializer=datastorage__pb2.FetchOrbRequest.FromString,
                    response_serializer=datastorage__pb2.OrbDataResponse.SerializeToString,
            ),
            'FetchOrbMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchOrbMeta,
                    request_deserializer=datastorage__pb2.FetchOrbRequest.FromString,
                    response_serializer=datastorage__pb2.OrbMetaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lunaricorn.orb.OrbDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lunaricorn.orb.OrbDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrbDataService(object):
    """Обновленный протокол с поддержкой Orb объектов
    """

    @staticmethod
    def PushData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lunaricorn.orb.OrbDataService/PushData',
            datastorage__pb2.PushDataRequest.SerializeToString,
            datastorage__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lunaricorn.orb.OrbDataService/PushMeta',
            datastorage__pb2.PushMetaRequest.SerializeToString,
            datastorage__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lunaricorn.orb.OrbDataService/FetchData',
            datastorage__pb2.FetchRequest.SerializeToString,
            datastorage__pb2.FetchDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lunaricorn.orb.OrbDataService/FetchMeta',
            datastorage__pb2.FetchRequest.SerializeToString,
            datastorage__pb2.FetchMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushOrbData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lunaricorn.orb.OrbDataService/PushOrbData',
            datastorage__pb2.OrbDataRequest.SerializeToString,
            datastorage__pb2.OrbResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushOrbMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lunaricorn.orb.OrbDataService/PushOrbMeta',
            datastorage__pb2.OrbMetaRequest.SerializeToString,
            datastorage__pb2.OrbResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchOrbData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lunaricorn.orb.OrbDataService/FetchOrbData',
            datastorage__pb2.FetchOrbRequest.SerializeToString,
            datastorage__pb2.OrbDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchOrbMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lunaricorn.orb.OrbDataService/FetchOrbMeta',
            datastorage__pb2.FetchOrbRequest.SerializeToString,
            datastorage__pb2.OrbMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
