name: Code Quality and Security

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy bandit safety

    - name: Run flake8 (code style)
      run: flake8 . --count --show-source --statistics --max-line-length=120

    - name: Run black (formatting)
      run: black . --check --diff

    - name: Run mypy (static typing)
      run: mypy . --ignore-missing-imports

    - name: Run bandit (security linter)
      run: bandit -r . -c pyproject.toml

    - name: Run safety (vulnerability scan)
      run: safety check -r requirements.txt --full-report

    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: code-analysis-reports
        path: |
          flake8_report.txt
          mypy_report.txt
          bandit_report.json
        retention-days: 3